### ISSUE TITLE
Add disabled state

### ISSUE THREAD

**Issue by ramadis** [crazycodeboy/react-native-check-box#13]
The checkbox needs a disabled state besides the basic _checked_/_unchecked_. Are you receiving pull requests?

**Comment by andrepcg** [comment]
This feature would be very useful

**Comment by sospedra** [comment]
PR here https://github.com/crazycodeboy/react-native-check-box/pull/35

**Comment by sospedra** [comment]
In the meantime the PR is merged you can install the fork by:

`npm install git+https://git@github.com/sospedra/react-native-check-box`
