### ISSUE TITLE
不支持联动单选

### ISSUE THREAD

**Issue by Notdefind** [crazycodeboy/react-native-check-box#23]
isChecked 绑定状态无效

**Comment by Liqiankun** [comment]
+ 1 我现在不能实现单选

**Comment by Liqiankun** [comment]
```
    onClick() {
        // this.setState({
        //     isChecked: !this.state.isChecked
        // })
        this.props.onClick();
    }

```
在react-native-check-box/index.js下修改就能显示单选了

**Comment by wangkang666** [comment]
此问题已解决 ,新增一个自定义属性进行判断 

static defaultProps = {
       isChecked: false,
       isChanged: true,
       leftTextStyle: {},
       rightTextStyle: {},
       key: true,
   }

onClick() {
       if (this.props.isChanged) {
           this.setState({
               isChecked: !this.state.isChecked
           })
       }
       this.props.onClick();
   }

**Comment by Liqiankun** [comment]
只要能解决都行！
