### ISSUE TITLE
CheckBox isChecked doesn't work expected.

### ISSUE THREAD

**Issue by SelfnessAid** [crazycodeboy/react-native-check-box#24]
I tried to display the checkbox with state that come from server. but checkbox doesn't work as expected.
When I try debug, all data come from server correctly.
for example, this.state.p_notifications = true after I get data from server. But still checkbox is unchecked even its isChecked = true.

Here is my code chip.
```
    constructor(props) {
        super(props);

        this.state = {
          p_notifications: false,
          t_notifications: false,
          messages: false,
          reservations: false,
          account: false,
          fro: false
        }
    }

    _getUser() {
      const { auth } = this.props;
      this.props.fetchUser(auth.user._id, auth.token).then(() => {
        const { api } = this.props;
        this.setState({
          p_notifications:(api.user.settings)?api.user.settings.notifications.push: false,
          t_notifications:(api.user.settings)?api.user.settings.notifications.text: false,
          messages:(api.user.settings)?api.user.settings.notifications.messages: false,
          reservations:(api.user.settings)?api.user.settings.notifications.reservations: false,
          account:(api.user.settings)?api.user.settings.notifications.activity: false,
          fro:(api.user.settings)?api.user.settings.notifications.recommandations: false,
        });
      });
    }

    componentWillMount() {
      this._getUser();
    }
 .................
            <CheckBox
                 style={styles.checkbox}
                 onClick={()=>{
                   if(this.state.t_notifications){
                     this.setState({t_notifications:false})
                   }else{
                     this.setState({t_notifications:true})
                   }
                   this._updateUserNotificaion()
                 }}
                 isChecked={this.state.t_notifications}
                 checkedImage={checked}
                 unCheckedImage={unchecked}
             />
```

Could you possibly let me know what's wrong with me ?

**Comment by ianhowe76** [comment]
I think this behaviour is fixed in the repository but not in npm

try setting your package.json to use "https://github.com/crazycodeboy/react-native-check-box.git"

**Comment by SelfnessAid** [comment]
@ianhowe76 
it works for me.
seems need to release next version :D

**Comment by azad-techvilla** [comment]
Facing same issue 

`
                                <View style={(this.state.activeTab==='domain')? {display:'flex'} : {display:'none'} } >
                                <FlatList
                                    data={this.props.data.industry}
                                    keyExtractor={(item, index) => index.toString()}
                                    renderItem={({ item }) => <View style={styles.filtChecRow}  key={item.value}><CheckBox
                                    style={styles.fieldCheck}
                                        onClick={() => {
                                            this.setState({
                                                isChecked: !this.state.isChecked
                                            })
                                        }}
                                        isChecked={this.state.isChecked}
                                        leftText={item.label}
                                    /></View>}
                                />
                                </View>

                                
                                <View style={(this.state.activeTab==='experience')? {display:'flex'} : {display:'none'} } >
                                <FlatList
                                    data={[
                                        {salary: '0 - 3 Lacs'},
                                        {salary: '3 - 6 Lacs'},
                                        {salary: '6 - 10 Lacs'},
                                        {salary: '10 - 15 Lacs'},
                                        {salary: '15 - 25 Lacs'},
                                        {salary: '25 - 50 Lacs'},
                                        {salary: '50 - 75 Lacs'},
                                        {salary: '75 - 100 Lacs'},
                                      ]}
                                    keyExtractor={(item, index) => index.toString()}
                                    renderItem={({ item }) => <View style={styles.filtChecRow}  key={item.value}><CheckBox
                                    style={styles.fieldCheck}
                                        onClick={() => {
                                            this.setState({
                                                isChecked: !this.state.isChecked
                                            })
                                        }}
                                        isChecked={this.state.isChecked}
                                        leftText={item.salary}
                                    /></View>}
                                />
                                </View>`


OnClick working and state changes but Check/Uncheck not render in 1st List but working fine with 2nd one 
In first one I am getting data from server 
I have updated my package.json  with 
` "react-native-check-box": "https://github.com/crazycodeboy/react-native-check-box.git",`
and run npm install 
but no luck
