### ISSUE TITLE
谢谢这么快就发布npm了，可是不能用

### ISSUE THREAD

**Issue by appbeijing** [crazycodeboy/react-native-check-box#4]
谢谢这么快就发布npm了，可是不能用，你是不是可以用es6语法改造一下代码

**Comment by crazycodeboy** [comment]
用的是ES6,你可以参考一下[examples](https://github.com/crazycodeboy/react-native-check-box/blob/master/examples/index.js)

**Comment by appbeijing** [comment]
但是我按照你的提示npm下来的不是啊，莫非有版本吗？

**Comment by crazycodeboy** [comment]
你说的不能用是指？
