### ISSUE TITLE
How do you change the colour of Checkbox?

### ISSUE THREAD

**Issue by raymondctc** [crazycodeboy/react-native-check-box#8]
From your demo, I see you can change the colour of checkboxes, however, I cannot find any API doing this. The only way I can change the colour of checkboxes is by setting `tintColor` inside the `<Image />` tag of your `genCheckedImage` function. Am I doing it wrong?

Thanks!

**Comment by crazycodeboy** [comment]
By specifying the tintColor for the `<Image />` like this 
```
<Image source={require('../../page/my/img/ic_check_box.png')} style={{tintColor: xxx}}
```
